task_name: eval
tags:
- dev
ckpt_path: submodules/text_recognition_lightning/models/resnet-orient2.ckpt
task: xml
datamodule:
  _target_: ${paths.target_src}.datamodules.xml_datamodule.NDLDataModule
  dataset:
    pred:
    - dataset_class: cli
  batch_size: 128
  num_workers: 1
  pin_memory: true
  batch_max_length: 40
  test_batch_max_length: 160
  test_max_width: 1600
  swap_bgr2rgb: true
  character_file: ${model.character_file}
  additional_elements:
  - BLOCK[@TYPE="柱"]
  - BLOCK[@TYPE="ノンブル"]
  - BLOCK[@TYPE="ルビ"]
model:
  _target_: ${paths.target_src}.models.ctc_module.OrientCTCLitModule
  character_file: submodules/text_recognition_lightning/ndldata/mojilist_NDL.txt
  ambiguous_char: 〓
  lr: 1.0
  batch_max_length: ${datamodule.batch_max_length}
  test_batch_max_length: ${datamodule.test_batch_max_length}
  net:
    _target_: ${paths.target_src}.models.components.resnet.ResNet_FeatureExtractor
    input_size: 3
    output_size: 512
callbacks:
  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar
  measuretime:
    _target_: ${paths.target_src}.callbacks.measure_time.MeasureTimeCallback
trainer:
  _target_: pytorch_lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 30
  val_check_interval: 0.2
  accelerator: gpu
  devices: 1
  deterministic: false
  benchmark: true
paths:
  root_dir: ${oc.env:PROJECT_DIR, ./}/submodules/text_recognition_lightning/
  target_src: submodules.text_recognition_lightning.src
  data_dir: ${paths.root_dir}/ndldata/
  log_dir: ${paths.root_dir}/logs/
  output_dir: /root/ocr_cli/ocr_b07
  work_dir: null
extras:
  ignore_warnings: false
  enforce_tags: true
  print_config: true
